# Generated by Django 5.2.17 on 2026-08-18 06:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'تصنيف مصروف',
                'verbose_name_plural': 'تصنيفات المصروفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم الفاتورة')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='البيان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المدفوع')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='الضريبة %')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPROVED', 'معتمدة'), ('PAID', 'مدفوعة'), ('CANCELLED', 'ملغاة')], default='APPROVED', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='الكود')),
                ('client_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='العميل')),
                ('client_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='هاتف العميل')),
                ('client_email', models.CharField(blank=True, max_length=120, null=True, verbose_name='بريد العميل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('PLANNING', 'تخطيط'), ('APPROVAL', 'قيد الموافقة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('INSPECTION', 'فحص'), ('ON_HOLD', 'متوقف'), ('CLOSED', 'مغلق')], default='IN_PROGRESS', max_length=20, verbose_name='الحالة')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الميزانية')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('estimated_end_date', models.DateField(blank=True, null=True, verbose_name='النهاية المتوقعة')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='النهاية الفعلية')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='النوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'نوع مشروع',
                'verbose_name_plural': 'أنواع المشاريع',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='اسم المستخدم')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('accountant', 'محاسب'), ('employee', 'موظف')], default='employee', max_length=20, verbose_name='الصلاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف إداري')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='البند')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7, verbose_name='الكمية')),
                ('unit', models.CharField(blank=True, default='قطعة', max_length=20, null=True, verbose_name='الوحدة')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفواتير',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.project', verbose_name='المشروع'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='البيان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المبلغ')),
                ('expense_date', models.DateField(verbose_name='تاريخ المصروف')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.expensecategory', verbose_name='التصنيف')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المبلغ')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفعة')),
                ('payment_method', models.CharField(blank=True, default='cash', max_length=50, null=True, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم السند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='البيان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('confirmed', 'مؤكدة'), ('pending', 'معلّقة'), ('cancelled', 'ملغاة')], default='confirmed', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'دفعة مشروع',
                'verbose_name_plural': 'دفعات المشاريع',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projecttype', verbose_name='النوع'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('employee_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='الرقم الوظيفي')),
                ('id_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم الهوية')),
                ('nationality', models.CharField(blank=True, max_length=60, null=True, verbose_name='الجنسية')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='الوظيفة')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الراتب الأساسي')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='أجر الساعة')),
                ('overtime_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='أجر الساعة الإضافية')),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=Decimal('1600'), max_digits=14, verbose_name='التأمين')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الخدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='core_worker_is_acti_2790c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='ساعات عادية')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='ساعات إضافية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_hours', to='core.project', verbose_name='المشروع')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='core.worker', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'ساعات عمل',
                'verbose_name_plural': 'ساعات العمل',
                'ordering': ['-date', 'worker__name'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المبلغ')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'دفعة فاتورة',
                'verbose_name_plural': 'دفعات الفواتير',
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['invoice'], name='core_invoic_invoice_3570be_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['project'], name='core_invoic_project_720086_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['project'], name='core_expens_project_d53b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpayment',
            index=models.Index(fields=['project', 'status'], name='core_projec_project_a78bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='core_projec_status_2020cc_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='core_projec_name_0563a9_idx'),
        ),
        migrations.AddIndex(
            model_name='workhour',
            index=models.Index(fields=['project'], name='core_workho_project_782f37_idx'),
        ),
        migrations.AddIndex(
            model_name='workhour',
            index=models.Index(fields=['worker'], name='core_workho_worker__8cfbbb_idx'),
        ),
        migrations.AddIndex(
            model_name='workhour',
            index=models.Index(fields=['date'], name='core_workho_date_50e747_idx'),
        ),
    ]
