# Generated by Django 5.2.17 on 2026-08-18 06:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('0'), max_digits=18, verbose_name='أجر الساعة'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='overtime_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='أجر الساعة الإضافية'),
        ),
    ]
