# Generated by Django 5.2.17 on 2026-08-19 14:30
"""Move from fixed roles to permission groups (auth.Group).

1. Create the module permissions (core.apppermission).
2. Create the default groups: مدير / محاسب / موظف.
3. Put every user in the group matching their old role, then drop the role
   column.
"""

from django.db import migrations, models

# A frozen copy of the permission registry as it was when this migration was
# written (core.permissions is deliberately not imported, so later code changes
# cannot alter what this migration does)
PERMISSIONS = [
    ("view_dashboard", "عرض لوحة المعلومات"),
    ("view_projects", "عرض المشاريع"),
    ("manage_projects", "إدارة المشاريع (إضافة وتعديل ودفعات ومصروفات)"),
    ("view_workers", "عرض الموظفين"),
    ("manage_workers", "إدارة الموظفين (إضافة وتعديل وإيقاف)"),
    ("manage_hours", "إدارة ساعات العمل (تسجيل وحذف)"),
    ("view_invoices", "عرض الفواتير"),
    ("manage_invoices", "إدارة الفواتير (إضافة وتعديل وحذف)"),
    ("view_compare", "مقارنة المشاريع"),
    ("view_reports", "تحميل تقارير المشاريع PDF"),
    ("manage_users", "إدارة المستخدمين والمجموعات"),
]

DEFAULT_GROUPS = {
    "مدير": [codename for codename, _ in PERMISSIONS],
    "محاسب": [codename for codename, _ in PERMISSIONS if codename != "manage_users"],
    "موظف": [],
}

ROLE_TO_GROUP = {"admin": "مدير", "accountant": "محاسب", "employee": "موظف"}


def create_groups_and_assign(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("core", "User")

    # auth.Permission rows are normally created after migrations run
    # (post_migrate), so they are created by hand here because this migration
    # needs them now.
    content_type, _ = ContentType.objects.get_or_create(
        app_label="core", model="apppermission"
    )
    permissions = {}
    for codename, name in PERMISSIONS:
        perm, _ = Permission.objects.get_or_create(
            codename=codename, content_type=content_type, defaults={"name": name}
        )
        permissions[codename] = perm

    groups = {}
    for group_name, codenames in DEFAULT_GROUPS.items():
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.set([permissions[c] for c in codenames])
        groups[group_name] = group

    for user in User.objects.all():
        group = groups[ROLE_TO_GROUP.get(user.role, "موظف")]
        user.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_worker_hourly_rate_alter_worker_overtime_rate'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'صلاحية النظام',
                'verbose_name_plural': 'صلاحيات النظام',
                'permissions': [('view_dashboard', 'عرض لوحة المعلومات'), ('view_projects', 'عرض المشاريع'), ('manage_projects', 'إدارة المشاريع (إضافة وتعديل ودفعات ومصروفات)'), ('view_workers', 'عرض الموظفين'), ('manage_workers', 'إدارة الموظفين (إضافة وتعديل وإيقاف)'), ('manage_hours', 'إدارة ساعات العمل (تسجيل وحذف)'), ('view_invoices', 'عرض الفواتير'), ('manage_invoices', 'إدارة الفواتير (إضافة وتعديل وحذف)'), ('view_compare', 'مقارنة المشاريع'), ('view_reports', 'تحميل تقارير المشاريع PDF'), ('manage_users', 'إدارة المستخدمين والمجموعات')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.RunPython(create_groups_and_assign, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
