# Generated by Django 5.2.17 on 2026-08-20 06:21
"""تفصيل الصلاحيات المجمّعة إلى صلاحيات دقيقة لكل إجراء.

كل صلاحية manage_* قديمة تُستبدل بصلاحيات الإجراءات المكوِّنة لها،
وتُنقل عضويات المجموعات تلقائياً ثم تُحذف الصلاحيات القديمة.
"""

from django.db import migrations

# نسخة ثابتة من السجل الجديد وقت كتابة الترحيل
NEW_PERMISSIONS = [
    ("view_dashboard", "عرض لوحة المعلومات"),
    ("view_projects", "عرض المشاريع وتفاصيلها"),
    ("add_project", "إضافة مشروع"),
    ("edit_project", "تعديل مشروع"),
    ("add_project_payment", "إضافة دفعة لمشروع"),
    ("add_project_expense", "إضافة مصروف لمشروع"),
    ("view_workers", "عرض الموظفين وتفاصيلهم"),
    ("add_worker", "إضافة موظف"),
    ("edit_worker", "تعديل بيانات موظف"),
    ("toggle_worker", "تفعيل وإيقاف موظف"),
    ("add_work_hours", "تسجيل ساعات عمل"),
    ("delete_work_hours", "حذف سجل ساعات"),
    ("view_invoices", "عرض الفواتير"),
    ("add_invoice", "إضافة فاتورة"),
    ("edit_invoice", "تعديل فاتورة"),
    ("delete_invoice", "حذف فاتورة"),
    ("view_compare", "مقارنة المشاريع"),
    ("view_reports", "تحميل تقارير المشاريع PDF"),
    ("view_users", "عرض المستخدمين"),
    ("add_user", "إضافة مستخدم"),
    ("edit_user", "تعديل مستخدم"),
    ("delete_user", "حذف مستخدم"),
    ("view_groups", "عرض المجموعات"),
    ("add_group", "إضافة مجموعة"),
    ("edit_group", "تعديل مجموعة وصلاحياتها"),
    ("delete_group", "حذف مجموعة"),
]

# الصلاحيات المجمّعة القديمة → الصلاحيات الدقيقة المكافئة
OLD_TO_NEW = {
    "manage_projects": ["add_project", "edit_project", "add_project_payment", "add_project_expense"],
    "manage_workers": ["add_worker", "edit_worker", "toggle_worker"],
    "manage_hours": ["add_work_hours", "delete_work_hours"],
    "manage_invoices": ["add_invoice", "edit_invoice", "delete_invoice"],
    "manage_users": [
        "view_users", "add_user", "edit_user", "delete_user",
        "view_groups", "add_group", "edit_group", "delete_group",
    ],
}


def split_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="core", model="apppermission"
    )

    new_perms = {}
    for codename, name in NEW_PERMISSIONS:
        perm, _ = Permission.objects.get_or_create(
            codename=codename, content_type=content_type, defaults={"name": name}
        )
        if perm.name != name:  # تحديث تسميات الصلاحيات الباقية
            perm.name = name
            perm.save(update_fields=["name"])
        new_perms[codename] = perm

    old_perms = Permission.objects.filter(
        content_type=content_type, codename__in=OLD_TO_NEW
    )
    for group in Group.objects.filter(permissions__in=old_perms).distinct():
        held = set(
            group.permissions.filter(content_type=content_type)
            .values_list("codename", flat=True)
        )
        for old_codename, replacements in OLD_TO_NEW.items():
            if old_codename in held:
                group.permissions.add(*[new_perms[c] for c in replacements])

    old_perms.delete()  # الحذف يزيل روابطها من المجموعات تلقائياً


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apppermission_remove_user_role'),
    ]

    operations = [
        migrations.RunPython(split_permissions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='apppermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_dashboard', 'عرض لوحة المعلومات'), ('view_projects', 'عرض المشاريع وتفاصيلها'), ('add_project', 'إضافة مشروع'), ('edit_project', 'تعديل مشروع'), ('add_project_payment', 'إضافة دفعة لمشروع'), ('add_project_expense', 'إضافة مصروف لمشروع'), ('view_workers', 'عرض الموظفين وتفاصيلهم'), ('add_worker', 'إضافة موظف'), ('edit_worker', 'تعديل بيانات موظف'), ('toggle_worker', 'تفعيل وإيقاف موظف'), ('add_work_hours', 'تسجيل ساعات عمل'), ('delete_work_hours', 'حذف سجل ساعات'), ('view_invoices', 'عرض الفواتير'), ('add_invoice', 'إضافة فاتورة'), ('edit_invoice', 'تعديل فاتورة'), ('delete_invoice', 'حذف فاتورة'), ('view_compare', 'مقارنة المشاريع'), ('view_reports', 'تحميل تقارير المشاريع PDF'), ('view_users', 'عرض المستخدمين'), ('add_user', 'إضافة مستخدم'), ('edit_user', 'تعديل مستخدم'), ('delete_user', 'حذف مستخدم'), ('view_groups', 'عرض المجموعات'), ('add_group', 'إضافة مجموعة'), ('edit_group', 'تعديل مجموعة وصلاحياتها'), ('delete_group', 'حذف مجموعة')], 'verbose_name': 'صلاحية النظام', 'verbose_name_plural': 'صلاحيات النظام'},
        ),
    ]
