# Generated by Django 5.2.17 on 2026-08-20 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


"""Manufacturing module: configurable workflow models, permissions and seeds.

The default seed data below can be changed from the interface later without
any code change:
    التصنيع: قص، تجميع
    التنفيذ النهائي: تركيب، تسليم
"""

# Permissions for the two new manufacturing modules — a frozen copy taken
# when this migration was written
OPERATIONAL_PERMS = [
    ("view_manufacturing", "عرض متابعة التصنيع"),
    ("add_manufacturing", "إنشاء متابعة تصنيع لمشروع"),
    ("update_manufacturing_stage", "تحديث حالة خطوة تصنيع"),
    ("add_manufacturing_note", "إضافة ملاحظات على خطوات التصنيع"),
]
CONFIG_PERMS = [
    ("view_manufacturing_config", "عرض إعدادات مراحل التصنيع"),
    ("add_manufacturing_phase", "إضافة مرحلة تصنيع"),
    ("edit_manufacturing_phase", "تعديل مرحلة تصنيع"),
    ("delete_manufacturing_phase", "حذف أو إيقاف مرحلة تصنيع"),
    ("add_manufacturing_stage", "إضافة خطوة تصنيع"),
    ("edit_manufacturing_stage", "تعديل خطوة تصنيع"),
    ("delete_manufacturing_stage", "حذف أو إيقاف خطوة تصنيع"),
    ("reorder_manufacturing", "إعادة ترتيب مراحل وخطوات التصنيع"),
]

# The default workflow — seed data only; no logic depends on these values
DEFAULT_WORKFLOW = [
    ("التصنيع", 1, [("قص", 1), ("تجميع", 2)]),
    ("التنفيذ النهائي", 2, [("تركيب", 1), ("تسليم", 2)]),
]


def seed_manufacturing(apps, schema_editor):
    """Create the permissions, grant them to the default groups, seed the
    workflow.

    Idempotent: it goes through get_or_create, so re-running creates no
    duplicates.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    ManufacturingPhase = apps.get_model("core", "ManufacturingPhase")
    ManufacturingStage = apps.get_model("core", "ManufacturingStage")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="core", model="apppermission"
    )
    created = {}
    for codename, name in OPERATIONAL_PERMS + CONFIG_PERMS:
        perm, _ = Permission.objects.get_or_create(
            codename=codename, content_type=content_type, defaults={"name": name}
        )
        created[codename] = perm

    # مدير gets every manufacturing permission; محاسب only the operational
    # ones, not the configuration
    admin_group = Group.objects.filter(name="مدير").first()
    if admin_group:
        admin_group.permissions.add(*created.values())
    accountant_group = Group.objects.filter(name="محاسب").first()
    if accountant_group:
        accountant_group.permissions.add(
            *[created[c] for c, _ in OPERATIONAL_PERMS]
        )

    for phase_name, phase_order, stages in DEFAULT_WORKFLOW:
        phase, _ = ManufacturingPhase.objects.get_or_create(
            name=phase_name, defaults={"order": phase_order}
        )
        for stage_name, stage_order in stages:
            ManufacturingStage.objects.get_or_create(
                phase=phase, name=stage_name, defaults={"order": stage_order}
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_apppermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'مرحلة تصنيع',
                'verbose_name_plural': 'مراحل التصنيع',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='apppermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_dashboard', 'عرض لوحة المعلومات'), ('view_projects', 'عرض المشاريع وتفاصيلها'), ('add_project', 'إضافة مشروع'), ('edit_project', 'تعديل مشروع'), ('add_project_payment', 'إضافة دفعة لمشروع'), ('add_project_expense', 'إضافة مصروف لمشروع'), ('view_workers', 'عرض الموظفين وتفاصيلهم'), ('add_worker', 'إضافة موظف'), ('edit_worker', 'تعديل بيانات موظف'), ('toggle_worker', 'تفعيل وإيقاف موظف'), ('add_work_hours', 'تسجيل ساعات عمل'), ('delete_work_hours', 'حذف سجل ساعات'), ('view_invoices', 'عرض الفواتير'), ('add_invoice', 'إضافة فاتورة'), ('edit_invoice', 'تعديل فاتورة'), ('delete_invoice', 'حذف فاتورة'), ('view_manufacturing', 'عرض متابعة التصنيع'), ('add_manufacturing', 'إنشاء متابعة تصنيع لمشروع'), ('update_manufacturing_stage', 'تحديث حالة خطوة تصنيع'), ('add_manufacturing_note', 'إضافة ملاحظات على خطوات التصنيع'), ('view_manufacturing_config', 'عرض إعدادات مراحل التصنيع'), ('add_manufacturing_phase', 'إضافة مرحلة تصنيع'), ('edit_manufacturing_phase', 'تعديل مرحلة تصنيع'), ('delete_manufacturing_phase', 'حذف أو إيقاف مرحلة تصنيع'), ('add_manufacturing_stage', 'إضافة خطوة تصنيع'), ('edit_manufacturing_stage', 'تعديل خطوة تصنيع'), ('delete_manufacturing_stage', 'حذف أو إيقاف خطوة تصنيع'), ('reorder_manufacturing', 'إعادة ترتيب مراحل وخطوات التصنيع'), ('view_compare', 'مقارنة المشاريع'), ('view_reports', 'تحميل تقارير المشاريع PDF'), ('view_users', 'عرض المستخدمين'), ('add_user', 'إضافة مستخدم'), ('edit_user', 'تعديل مستخدم'), ('delete_user', 'حذف مستخدم'), ('view_groups', 'عرض المجموعات'), ('add_group', 'إضافة مجموعة'), ('edit_group', 'تعديل مجموعة وصلاحياتها'), ('delete_group', 'حذف مجموعة')], 'verbose_name': 'صلاحية النظام', 'verbose_name_plural': 'صلاحيات النظام'},
        ),
        migrations.CreateModel(
            name='Manufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing', to='core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'متابعة تصنيع',
                'verbose_name_plural': 'متابعات التصنيع',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.manufacturingphase', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'خطوة تصنيع',
                'verbose_name_plural': 'خطوات التصنيع',
                'ordering': ['phase__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingStageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التنفيذ'), ('done', 'مكتمل')], default='not_started', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('manufacturing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.manufacturing', verbose_name='المتابعة')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.manufacturingstage', verbose_name='الخطوة')),
            ],
            options={
                'verbose_name': 'سجل خطوة تصنيع',
                'verbose_name_plural': 'سجلات خطوات التصنيع',
                'constraints': [models.UniqueConstraint(fields=('manufacturing', 'stage'), name='uniq_manufacturing_stage')],
            },
        ),
        migrations.RunPython(seed_manufacturing, migrations.RunPython.noop),
    ]
