# Generated by Django 5.2.17 on 2026-08-30 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_manufacturingphase_alter_apppermission_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "قيد الانتظار"),
                            ("running", "جارٍ الإنشاء"),
                            ("done", "جاهز"),
                            ("failed", "فشل"),
                        ],
                        default="queued",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/",
                        verbose_name="الملف",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="رسالة الخطأ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الطلب"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="بدأ التنفيذ"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="انتهى"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_jobs",
                        to="core.project",
                        verbose_name="المشروع",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="طلبه",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب تقرير",
                "verbose_name_plural": "طلبات التقارير",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="core_report_project_71e0b5_idx",
                    )
                ],
            },
        ),
    ]
