# Generated by Django 5.2.17 on 2026-09-09 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


"""The activity log: its table, and the permission that opens it.

The seed below follows the pattern of 0005 — a frozen copy of the new
permission, created and granted here so the default groups are right the moment
this migration finishes, instead of waiting for post_migrate.
"""

# A frozen copy of the permission this migration adds to the التقارير module
ACTIVITY_PERM = ("view_activity", "عرض حركة الأنشطة")


def seed_activity_permission(apps, schema_editor):
    """Create the permission and grant it to مدير and محاسب.

    Idempotent: it goes through get_or_create, so re-running creates no
    duplicates.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="core", model="apppermission"
    )
    codename, name = ACTIVITY_PERM
    permission, _ = Permission.objects.get_or_create(
        codename=codename, content_type=content_type, defaults={"name": name}
    )

    # The activity log is a reporting screen, not system administration, so
    # both مدير and محاسب get it — the same split التقارير already has.
    for group_name in ("مدير", "محاسب"):
        group = Group.objects.filter(name=group_name).first()
        if group:
            group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reportjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_dashboard', 'عرض لوحة المعلومات'), ('view_projects', 'عرض المشاريع وتفاصيلها'), ('add_project', 'إضافة مشروع'), ('edit_project', 'تعديل مشروع'), ('add_project_payment', 'إضافة دفعة لمشروع'), ('add_project_expense', 'إضافة مصروف لمشروع'), ('view_workers', 'عرض الموظفين وتفاصيلهم'), ('add_worker', 'إضافة موظف'), ('edit_worker', 'تعديل بيانات موظف'), ('toggle_worker', 'تفعيل وإيقاف موظف'), ('add_work_hours', 'تسجيل ساعات عمل'), ('delete_work_hours', 'حذف سجل ساعات'), ('view_invoices', 'عرض الفواتير'), ('add_invoice', 'إضافة فاتورة'), ('edit_invoice', 'تعديل فاتورة'), ('delete_invoice', 'حذف فاتورة'), ('view_manufacturing', 'عرض متابعة التصنيع'), ('add_manufacturing', 'إنشاء متابعة تصنيع لمشروع'), ('update_manufacturing_stage', 'تحديث حالة خطوة تصنيع'), ('add_manufacturing_note', 'إضافة ملاحظات على خطوات التصنيع'), ('view_manufacturing_config', 'عرض إعدادات مراحل التصنيع'), ('add_manufacturing_phase', 'إضافة مرحلة تصنيع'), ('edit_manufacturing_phase', 'تعديل مرحلة تصنيع'), ('delete_manufacturing_phase', 'حذف أو إيقاف مرحلة تصنيع'), ('add_manufacturing_stage', 'إضافة خطوة تصنيع'), ('edit_manufacturing_stage', 'تعديل خطوة تصنيع'), ('delete_manufacturing_stage', 'حذف أو إيقاف خطوة تصنيع'), ('reorder_manufacturing', 'إعادة ترتيب مراحل وخطوات التصنيع'), ('view_compare', 'مقارنة المشاريع'), ('view_reports', 'تحميل تقارير المشاريع PDF'), ('view_activity', 'عرض حركة الأنشطة'), ('view_users', 'عرض المستخدمين'), ('add_user', 'إضافة مستخدم'), ('edit_user', 'تعديل مستخدم'), ('delete_user', 'حذف مستخدم'), ('view_groups', 'عرض المجموعات'), ('add_group', 'إضافة مجموعة'), ('edit_group', 'تعديل مجموعة وصلاحياتها'), ('delete_group', 'حذف مجموعة')], 'verbose_name': 'صلاحية النظام', 'verbose_name_plural': 'صلاحيات النظام'},
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الحدث')),
                ('actor_name', models.CharField(blank=True, max_length=100, verbose_name='اسم المنفّذ')),
                ('action', models.CharField(choices=[('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف'), ('status', 'تغيير حالة'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج')], max_length=20, verbose_name='الإجراء')),
                ('target_type', models.CharField(choices=[('project', 'مشروع'), ('worker', 'موظف'), ('invoice', 'فاتورة'), ('payment', 'دفعة'), ('expense', 'مصروف'), ('work_hours', 'ساعات عمل'), ('manufacturing', 'متابعة تصنيع'), ('stage_record', 'خطوة تصنيع'), ('phase', 'مرحلة تصنيع'), ('stage', 'خطوة في الإعدادات'), ('user', 'مستخدم'), ('group', 'مجموعة'), ('report', 'تقرير'), ('session', 'جلسة')], max_length=20, verbose_name='نوع العنصر')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم العنصر')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='العنصر')),
                ('description', models.CharField(max_length=300, verbose_name='التفاصيل')),
                ('project_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المشروع')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'حدث',
                'verbose_name_plural': 'حركة الأنشطة',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'), models.Index(fields=['project'], name='core_activi_project_06e9d9_idx'), models.Index(fields=['actor'], name='core_activi_actor_i_ae131c_idx'), models.Index(fields=['target_type'], name='core_activi_target__4568ee_idx')],
            },
        ),
        migrations.RunPython(seed_activity_permission, migrations.RunPython.noop),
    ]
