# Generated by Django 5.2.17 on 2026-09-16 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


"""Per-user dashboard settings, and the permissions that open a booked
payment or expense to editing and deletion.

The permissions are seeded here the way 0005 and 0007 do it — a frozen copy
created and granted in the migration — so the groups are correct the moment it
finishes rather than after the next post_migrate.
"""

# Frozen copies of the permissions this migration adds to the المشاريع module
RECORD_PERMISSIONS = [
    ("edit_project_payment", "تعديل دفعة مشروع"),
    ("delete_project_payment", "حذف دفعة مشروع"),
    ("edit_project_expense", "تعديل مصروف مشروع"),
    ("delete_project_expense", "حذف مصروف مشروع"),
]


def seed_record_permissions(apps, schema_editor):
    """Create the permissions and grant them to مدير alone.

    Rewriting or erasing a payment that is already booked against a project
    changes what the project cost, so it starts with the manager only. This is
    a starting point, not a rule: the manager hands either permission to any
    group from the groups screen.

    Idempotent — it goes through get_or_create, so re-running adds nothing.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="core", model="apppermission"
    )
    created = [
        Permission.objects.get_or_create(
            codename=codename, content_type=content_type, defaults={"name": name}
        )[0]
        for codename, name in RECORD_PERMISSIONS
    ]

    manager = Group.objects.filter(name="مدير").first()
    if manager:
        manager.permissions.add(*created)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_apppermission_options_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_dashboard', 'عرض لوحة المعلومات'), ('view_projects', 'عرض المشاريع وتفاصيلها'), ('add_project', 'إضافة مشروع'), ('edit_project', 'تعديل مشروع'), ('add_project_payment', 'إضافة دفعة لمشروع'), ('edit_project_payment', 'تعديل دفعة مشروع'), ('delete_project_payment', 'حذف دفعة مشروع'), ('add_project_expense', 'إضافة مصروف لمشروع'), ('edit_project_expense', 'تعديل مصروف مشروع'), ('delete_project_expense', 'حذف مصروف مشروع'), ('view_workers', 'عرض الموظفين وتفاصيلهم'), ('add_worker', 'إضافة موظف'), ('edit_worker', 'تعديل بيانات موظف'), ('toggle_worker', 'تفعيل وإيقاف موظف'), ('add_work_hours', 'تسجيل ساعات عمل'), ('delete_work_hours', 'حذف سجل ساعات'), ('view_invoices', 'عرض الفواتير'), ('add_invoice', 'إضافة فاتورة'), ('edit_invoice', 'تعديل فاتورة'), ('delete_invoice', 'حذف فاتورة'), ('view_manufacturing', 'عرض متابعة التصنيع'), ('add_manufacturing', 'إنشاء متابعة تصنيع لمشروع'), ('update_manufacturing_stage', 'تحديث حالة خطوة تصنيع'), ('add_manufacturing_note', 'إضافة ملاحظات على خطوات التصنيع'), ('view_manufacturing_config', 'عرض إعدادات مراحل التصنيع'), ('add_manufacturing_phase', 'إضافة مرحلة تصنيع'), ('edit_manufacturing_phase', 'تعديل مرحلة تصنيع'), ('delete_manufacturing_phase', 'حذف أو إيقاف مرحلة تصنيع'), ('add_manufacturing_stage', 'إضافة خطوة تصنيع'), ('edit_manufacturing_stage', 'تعديل خطوة تصنيع'), ('delete_manufacturing_stage', 'حذف أو إيقاف خطوة تصنيع'), ('reorder_manufacturing', 'إعادة ترتيب مراحل وخطوات التصنيع'), ('view_compare', 'مقارنة المشاريع'), ('view_reports', 'تحميل تقارير المشاريع PDF'), ('view_activity', 'عرض حركة الأنشطة'), ('view_users', 'عرض المستخدمين'), ('add_user', 'إضافة مستخدم'), ('edit_user', 'تعديل مستخدم'), ('delete_user', 'حذف مستخدم'), ('view_groups', 'عرض المجموعات'), ('add_group', 'إضافة مجموعة'), ('edit_group', 'تعديل مجموعة وصلاحياتها'), ('delete_group', 'حذف مجموعة')], 'verbose_name': 'صلاحية النظام', 'verbose_name_plural': 'صلاحيات النظام'},
        ),
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('3m', 'آخر ٣ شهور'), ('6m', 'آخر ٦ شهور'), ('12m', 'آخر ١٢ شهر'), ('year', 'السنة الحالية'), ('all', 'كل البيانات')], default='6m', max_length=10, verbose_name='فترة البيانات')),
                ('include_closed_projects', models.BooleanField(default=False, verbose_name='تضمين المشاريع المغلقة')),
                ('top_projects_count', models.PositiveSmallIntegerField(default=5, verbose_name='عدد المشاريع في «أعلى تكلفة»')),
                ('active_projects_count', models.PositiveSmallIntegerField(default=8, verbose_name='عدد صفوف «المشاريع قيد التنفيذ»')),
                ('activity_count', models.PositiveSmallIntegerField(default=10, verbose_name='عدد صفوف «آخر الأحداث»')),
                ('only_own_activity', models.BooleanField(default=False, verbose_name='عرض أحداثي أنا فقط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات لوحة المعلومات',
                'verbose_name_plural': 'إعدادات لوحة المعلومات',
            },
        ),
        migrations.RunPython(seed_record_permissions, migrations.RunPython.noop),
    ]
